### ISSUE TITLE
Download progress bar doesn't follow accent color

### ISSUE THREAD

**Issue by Keith94** [mr-islam/zen-fox#9]
Hey @mr-islam, would it be possible to style the progress bars in the downloads panel? they default to blue on my system but don't match my magenta accent color.

![firefox_2018-05-29_12-49-02](https://user-images.githubusercontent.com/5490615/40682685-51a9cae2-6341-11e8-9869-24501da710ad.png)

**Comment by mr-islam** [comment]
I wish that was possible @Keith94, but those progress bars appear to be themed based the system theme. I can switch mine from blue to purple by changing my system's GTK theme from Adapta to Lavender, for example (sorry I couldn't take a screenshot, because the entire panel would close when I pressed the hotkey)

I'll try filing this on Bugzilla so that Firefox devs can add a way to theme those progress bars

**Comment by mr-islam** [comment]
Submitted, it's [Bug #1465320](https://bugzilla.mozilla.org/show_bug.cgi?id=1465320)

**Comment by Keith94** [comment]
I was afraid of that; nevertheless, thanks for filing that issue! Fingers crossed they get to it :-)

Meanwhile I found a workaround by editing [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) to override the colors.
If anyone's interested in the code:

```css
.downloadProgress {
    -moz-appearance: none !important;
    background: -moz-dialog !important;
}
.downloadProgress > .progress-bar {
    -moz-appearance: none !important;
    background: #D33682 !important;
}
.downloadProgress > .progress-remainder {
    -moz-appearance: none !important;
    background: transparent !important;
}
.downloadProgress[paused="true"] > .progress-bar {
    background: GrayText !important;
}
```

Result:

![firefox_2018-05-29_22-47-01](https://user-images.githubusercontent.com/5490615/40701417-b82de9dc-6392-11e8-8af2-c55bfb99591d.png)
